config/routes.rb
Gables::Application.routes.draw do

  devise_for :users
  match '/admin/clear_cache' => 'application#clear_cache'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  constraints :subdomain => /^tablet/ do
    root  :to => 'tablet/properties#index'
    resources :properties, :only => [:index, :show, :edit], :as => "tablet_properties", :module => "tablet" do
      get 'manifest', :on => :member, :as => 'manifest'
      get "floorplans", :on => :member
      get "options", :on => :member
      post "email_brochure", :on => :member
      post "email_pdf", :on => :member
      resources :units, :only => [:index] do
        post "expire", :on => :collection
        get "nearby", :on => :collection
      end
    end
    resources :guests, :as => "tablet_guests", :module => "tablet"
    match 'samples' => "tablet/properties#samples"

    post 'sessions/create' => "tablet/sessions#create", :as => "tablet_create_sessions"
    put  'sessions' => "tablet/sessions#update"
    get  'sessions/status' => "tablet/sessions#status"
    post 'sessions/destroy' => "tablet/sessions#destroy"
    match "/find-guest" => "tablet/insite#find_guest"
    match "/guest-card" => "tablet/insite#guest_card"
    post "/submit-guest-card" => "tablet/insite#submit_guest_card"
  end

  constraints :subdomain => /urban/ do
    root :to => 'urban/home#index'
    match 'modal/contact'       => 'modal#contact'
    match 'modal/thankyou'      => 'modal#thankyou'
    match 'home/site_search'    => 'urban/home#site_search'
    match 'properties'          => 'urban/home#properties'
    match 'find/apartment/:id'  => 'urban/find#community'
    match 'find/where'  => 'urban/find#where'
    match 'modal/video'         => 'modal#video'
    match 'company/news/:id'    => 'company#news_show', :as => 'post'
    match 'company/news'        => 'company#news',      :as => 'posts'
    match ':section/p/:path'    => 'urban/pages#show', :as => 'urban_page',
          :constraints => {:section => /services|toplevel/}
  end

  constraints :subdomain => /gca/ do
    root  :to                   => 'gca/home#index'
    match 'gallery'             => 'gca/home#gallery'
    post 'contact'             => 'gca/home#contact'
    match 'modal/contact'       => 'modal#contact'
    match 'modal/thankyou'      => 'modal#thankyou'
    match 'find/where'          => 'gca/find#where'
    match 'find/listing/:id'  => 'gca/find#community', :as => 'listing'
    match 'find/walkscore/:id'  => 'find#walkscore', :as => 'walkscore'
    match 'modal/video'         => 'modal#video'
    match 'home/site_search'    => 'gca/home#site_search'
    post 'home/maintenance_request'  => 'gca/home#maintenance'
    post 'home/lease_request'  => 'gca/home#lease'
    match 'thank_you'           => 'gca/home#thank_you'
    match 'company/news/:id'    => 'company#news_show', :as => 'post'
    match 'company/news'        => 'company#news',      :as => 'posts'
    match 'equal_employment'    => 'home#equal_employment', :as => 'equal_employment'
    match ':section/p/:path'    => 'gca/pages#show', :as => 'gca_page',
          :constraints => {:section => /services|toplevel/}

    match '/gca-living.aspx'                                => redirect('/toplevel/p/our_company')
    match '/gca-gablesservices.aspx'                        => redirect('/services/p/guest_services')
    match '/gca-careers.aspx'                               => redirect('http://gables.com/careers/p/careers_overview')
    match '/gca-contactus.aspx'                             => redirect('/toplevel/p/our_company')
    match '/home.aspx'                                      => redirect('/')
    match '/gca-living/gca-reservation.aspx'                => redirect('/contact')
    match '/gca-living/gca-furnishings.aspx'                => redirect('/gallery')
    match '/gca-living/gca-tour.aspx'                       => redirect('/gallery')
    match '/gca-living/gca-faq.aspx'                        => redirect('/services/p/how_it_works')
    match '/gca-gablesservices/gca-servicerequest.aspx'     => redirect('/services/p/guest_services')
    match '/gca-gablesservices/gca-testimonials.aspx'       => redirect('/services/p/how_it_works')
    match '/gca-gablesservices/gca-vacate.aspx'             => redirect('/services/p/guest_services')
    match '/gca-living/green-initiatives.aspx'             => redirect('http://gables.com/life/p/green_initiatives')

  end

  constraints :subdomain => /(?!gca|urban|tablet)/ do
    root :to => 'find#index'

    get "language" => "home#language"
    match 'contact'           => 'home#contact'
    match 'tablet'            => 'home#tablet'
    match 'equal_employment'  => 'home#equal_employment', :as => 'equal_employment'
    match 'privacy'           => 'home#privacy',          :as => 'privacy'
    match 'vaultware'         => 'home#vaultware',        :as => 'vaultware'
    match 'recent_searches'   => 'home#recent_searches',  :as => 'recent_searches'

    match ':section/p/:path'  => 'pages#show', :as => 'page',
          :constraints => {:section => /life|company|careers/}

    match   'find/apartment/:id'  => 'find#community', :as => 'property'
    match   'find/floorplan/:id'  => 'find#floorplan', :as => 'floorplan'
    match   'find/walkscore/:id'  => 'find#walkscore', :as => 'walkscore'

    match   'yelp/:id'  => 'find#yelp', :as => 'yelp'

    namespace 'find' do
      get   'where'
      post  'where'
      get   'comparison'
      get   'request_hold'
      get   'floorplans_serp'
    end

    namespace 'home' do
      get   'site_search'
      get   'empty'
    end

    namespace 'life' do
      get 'why_gables'
    end

    match 'company/news/:id'  => 'company#news_show', :as => 'post'
    match 'company/news'      => 'company#news',      :as => 'posts'

    namespace 'modal' do
      get   'thankyou'
      get   'contact'
      get   'video'
      get   'executive'
      post   'contact'
    end

    namespace 'sectionals' do
      get   'header'
      get   'footer'
    end

    namespace 'associates' do
      get   'show'
    end

    match   'associates/show/:id'  => 'associates#show', :as => 'associate'
    get 'sitemap.:format' => 'sitemap#show', :as => :sitemap, :constraints => {:format => 'xml'}

    match '/find/community/:any'                          => redirect('/find/apartment/%{any}')
    match '/aboutus.aspx'                                 => redirect('/life/p/why_gables')
    match '/aboutus/awards.aspx'                          => redirect('/company/news')
    match '/aboutus/community-service.aspx'               => redirect('/life/p/community_service')
    match '/aboutus/company-overview.aspx'                => redirect('/company/p/corporate_overview')
    match '/aboutus/company-philosophy.aspx'              => redirect('/life/p/why_gables')
    match '/aboutus/construction-and-development.aspx'    => redirect('/company/p/real_estate')
    match '/aboutus/copyright.aspx'                       => redirect('/privacy')
    match '/aboutus/gablesgreeninitiative.aspx'           => redirect('/life/p/green_initiatives')
    match '/aboutus/gablesgreeninitiative/earthday.aspx'  => redirect('/life/p/green_initiatives')
    match '/aboutus/gablesmessage.aspx'                   => redirect('/life/p/community_service')
    match '/aboutus/in-the-news.aspx'                     => redirect('/company/news')
    match '/aboutus/investmentstrategy.aspx'              => redirect('/company/p/real_estate')
    match '/aboutus/officers.aspx'                        => redirect('/company/p/corporate_executives')
    match '/aboutus/privacypolicy.aspx'	                  => redirect('/privacy')
    match '/aboutus/property-management.aspx'	            => redirect('/company/p/real_estate')
    match '/aboutus/sitemap.aspx'	                        => redirect('/')
    match '/aboutus/whotocontact.aspx'	                  => redirect('/company/p/corporate_contacts')
    match '/admin.:any'	                                  => redirect('/admin')
    match '/apartment-living/:any/:any'	                  => redirect('/life/p/why_gables')
    match '/around-town/:any/:any'                        => redirect('/')
    match '/careers.aspx'	                                => redirect('/careers/p/careers_overview')
    match '/carrers.aspx'	                                => redirect('/careers/p/careers_overview')
    match '/careers'                                      => redirect('/careers/p/search')
    match '/contactus.:any'	                              => redirect('/company/p/corporate_contacts')
    match '/gablesliving/:any'	                          => redirect('/life/p/why_gables')
    match '/gablesservices.:any'	                        => redirect('/company/p/corporate_overview')
    match '/gca-:any'	                                    => redirect('http://gca.gables.com/')
    match '/holiday2010/:any'                             => redirect('/')
    match '/home'	                                        => redirect('/')
    match '/index.:any'                                   => redirect('/')
    match '/intersource:any'                              => redirect('/')
    match '/jobs/:any'	                                  => redirect('/careers/p/careers_overview')
    match '/new:any'	                                    => redirect('/')
    match '/onlineleasing/:any'	                          => redirect('https://extra.gables.com/portal/')
    match '/portallogin.:any'                             => redirect('https://extra.gables.com/portal/')
    match '/post/:any'                                  	=> redirect('http://blog.gables.com/')
    match '/RequestConfirm.:any'	                        => redirect('/')
    match '/RequestPreQualify.:any'	                      => redirect('/')
    match '/RequestToHold.:any'                         	=> redirect('/')
    match '/RequestVIP.:any'                            	=> redirect('/')

app/controllers/gca/find_controller.rb
class Gca::FindController < Gca::ApplicationController
  layout 'gca/application'
  
  def where
    @region = Gca::Region.find_by_city_and_state(params[:city], params[:state])
    if @region && @region.properties.published.length > 0
      @section = 'properties'
      @query = "#{params[:city]} #{params[:state]}"
      @properties = @region.properties.published.paginate(:per_page => 3, :page => params[:page] || 1)
    else
      redirect_to url_for(:controller => 'gca/home', :action => 'contact', :subdomain => 'gca')
    end
  end
  
  def community
    @section = 'properties'
    @property = Property.published.find params[:id]
    @green_categories = GreenCategory.order('position ASC')
  rescue ActiveRecord::RecordNotFound
    error_404
  end
end

app/controllers/urban/find_controller.rb
class Urban::FindController < ApplicationController
  layout 'urban/application'
  
  def community
    @section = 'properties'
    @property = Urban::Property.find params[:id]
  rescue ActiveRecord::RecordNotFound
    error_404
  end
  
  
  def where
    @section = 'properties'
    
    @properties = Urban::Property.where("street like '#{params[:query]}' or city like '#{params[:query]}' or state like '#{params[:query]}' or zip like '#{params[:query]}'").order('position ASC')
    @cities = Urban::Property.select("DISTINCT(city)").order('city').map(&:city)
  end
  
  
end

app/helpers/find_helper.rb
module FindHelper
  def h1
    @h1 = if @s.properties.length > 0
      "<strong>&ldquo;#{@query}&rdquo;</strong> Apartments; we found #{pluralize(@s.properties.length, 'community')}"
    else
      if params[:beds].blank? && params[:baths].blank? && params[:rent_min].blank? && params[:rent_max].blank? && params[:pet_friendly].blank? && params[:amenities].blank? && params[:features].blank? && params[:order].blank? && params[:floorplans].blank?
      "Your search for <strong>&ldquo;#{@query}&rdquo;</strong>returned no results. Select from one of our locations below or try a new search."
      else
        "Your filtered search for <strong>&ldquo;#{@query}&rdquo;</strong>returned no results. Select from one of our locations below or try a new search."
      end
    end
  end

  def rooms(floorplan)
    if floorplan.bedrooms_count == 0
      "Studio"
    else
      "#{floorplan.bedrooms_count} Bedroom / #{floorplan.bathrooms_count} Bath"
    end
  end

  def area(unit)
    if unit.area_min == unit.area_max
      unit.area_min
    elsif unit.area_max
      "#{unit.area_min} - #{unit.area_max}"
    else
      unit.area_min
    end
  end

  def reserve_prequalify_url unit, floorplan, property
    "#{property.website}/?module=check_availability&property_floorplan[id]=#{floorplan.gables_id}&unit_space[id]=#{unit.gables_id}&from_property_info=1&floorplan_availability_filter[number_of_bedrooms]=&floorplan_availability_filter[number_of_occupants]=1"
  end

  def apply_online_url unit
    "http://extra.gables.com/Onlineleasing/007_DS_Inbound.aspx?PUNIT_PSI_ID=#{unit.gables_id}" 
  end

  def notify_me_when_available_url floorplan, property
    "#{property.website}/Apartments/module/guest_card/property[id]/#{property.gables_id}/pf[id]/#{floorplan.gables_id}/from_check_availability/1/is_availability_alert/1/lightwindow/1/"
  end

end

app/views/find/_community_amenities.html.haml
.amenities
  - if @shopping_etc
    %h3#shopping-dining.jump Shopping &amp; Dining
    = raw @shopping_etc
    %p= link_to @property.urban_property.name, property_url(@property.urban_property, :subdomain => "urban"), :target => "urban"
  %h3 Community Amenities
  .list_columns
    - @property.amenities.in_groups_of((@property.amenities.length+2)/2) do |amenities|
      %ul
        - amenities.each do |amenity|
          - if amenity
            %li= "#{amenity.description}"

  - if params[:controller].include? "gca"
    %h3#pet_policy.jump Pet Policy
    %p
      Gables Corporate Accommodations is happy to accept dogs and/or cats with a maximum of two.
      Breed and weight restrictions apply per the community chosen for your stay.  A pet fee will
      be required and a Pet Addendum must be signed. Service animals assisting handicapped persons
      are allowed and no pet fee is required.
  - elsif (@property.allows_cats? || @property.allows_dogs?) && !@property.pet_policy.blank?
    %h3#pet_policy Pet Policy
    %p= @property.pet_policy

  - unless @property.community_programs.blank?
    %h3 Community Programs
    %p= raw(@property.community_programs.gsub("\n", "<br />"))

  - unless @property.green_initiatives.blank?
    %h3#green_initiatives.jump Green Initiatives
    - @green_categories.each do |green_category|
      - initiatives = @property.green_initiatives.where(:green_category_id => green_category.id)
      - if initiatives.length > 0
        %h4= green_category.name
        .list_columns
          - initiatives.in_groups_of((initiatives.length+2)/2) do |records|
            %ul
              - records.each do |initiative|
                - if initiative
                  %li= raw("#{initiative.name}")
= render :partial => '/find/community_brochures'
%a{:href => '#', :class => 'toggle'} all amenities +

app/views/find/_community_brochures.html.haml
.brochures
  %ul
    - unless @property.full_brochure_url.blank? && @property.short_brochure_url.blank? && @property.resident_brochure_url.blank?
      %li Brochures:
    - if @property.full_brochure.url
      %li.brochure= link_to 'Floorplans', @property.full_brochure.url
    - if @property.short_brochure.url
      %li.brochure= link_to 'Community', @property.short_brochure.url
    - if @property.resident_brochure.url
      %li.brochure= link_to 'For Residents', @property.resident_brochure.url

app/views/find/_community_life.html.haml
#tumblr_feed.blog
  %h2 
    Life at
    = @property.name
  .hfeed
  - unless @property.nil? || (!@property.nil? && @property.blog_url.blank?)
    %p.blog_link= link_to 'More from the blog', @property.blog_url
  - else
    %p.blog_link= link_to 'More from the blog', 'http://blog.gables.com/'

app/views/find/_community_results.haml
- @properties.each do |property|
  .community_result[property]{:itemscope => true, :itemtype => 'http://schema.org/Residence'}
    .community_info
      .thumb{:itemprop => 'image'}
        - if property.images.count > 0
          = link_to image_tag(property.images.first.thumb.url, :alt => ''), property_path(property)
        - else
          = link_to image_tag('no_image.gif', :alt => ''), property_path(property)
      .details
        %h2{:itemprop => 'name'}= link_to property.name, property_path(property)
        - unless property.short_description.blank? && property.long_description.blank?
          %p= property.short_description != '' ? raw(property.short_description) : raw(property.long_description)
        - unless !property.allows_dogs? && !property.allows_cats?
          .pets
            - if property.allows_dogs? && property.allows_cats?
              %p
                = image_tag 'dogs_cats.gif', :alt => ''
                Allows dogs & cats
            - elsif property.allows_dogs? && !property.allows_cats?
              %p
                = image_tag 'dogs.gif', :alt => ''
                Allows dogs
            - elsif !property.allows_dogs? && property.allows_cats?
              %p
                = image_tag 'cats.gif', :alt => ''
                Allows cats
        %h3 Top Amenities
        %ul
          - property.amenities.limit(5).each do |amenity|
            %li= "- #{amenity.description}"
    .actions
      %ul
        %li.compare
          = check_box_tag :compare_options, property.id, false, :title => property.name, :class => 'community'
          = label_tag :compare_options, 'Compare'
        %li.map
          %a{:href => '#map_canvas', :data => {:id => property.id}} 'Show on Map'
        %li.visit= link_to 'Schedule a Visit', property_path(property, :anchor => 'drop_schedule_visit')
        %li.community= link_to 'View Community', property_path(property)
    .floorplans
    .summary
      %p #{pluralize(@s.floorplans_for(property).length, 'Floorplan')} available

app/views/find/_floorplan_results.haml
- @properties.each do |property|
  - floorplans = @s.floorplans_for(property).order('rent_min')
  - floorplans.each do |floorplan|
    .floorplan_result
      .floorplan_info
        .thumb
          - if floorplan.images.count > 0
            = image_tag floorplan.images.first.thumb.url, :alt => ''
            = link_to 'show large image', floorplan.images.first.thumb.url
          - else
            = image_tag 'no_image.gif', :alt => ''
        .details
          %h2= link_to raw("#{floorplan.name} <span>#{rooms(floorplan)}</span>"), floorplan_path(floorplan)
          %p at #{link_to property.name, property_path(property)}
          %h3 Available Features
          %ul
            - property.amenities.each do |amenity|
              %li= "- #{amenity.description}"
      = render :partial => 'floorplan_table', :locals => {:floorplan => floorplan, :include_compare => true}

app/views/find/_maps.html.haml
:plain
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
= javascript_include_tag 'map'
%script{:type => 'text/javascript'}
  $(function() {
  - if regions && regions.length > 0
    GMap.zoom = 4;
    GMap.center = new google.maps.LatLng(41.59,-93.62);
    GMap.initialize();
    var regions = [];
    - regions.each do |region|
      = "regions.push({"+                     |
          "id: '#{region.id}',"+              |
          "lat: #{region.latitude},"+         |
          "lng: #{region.longitude},"+        |
          "name: '#{region.name}'"+           |
        "});"                                 |
    GMap.addCityMarkers(regions);
  - else
    GMap.use_bounds = true;
    GMap.zoom = 11;
    GMap.initialize();
    var points = [];
    - if properties && properties.length > 0
      - properties.reverse.each do |property|
        = "points.push({"+                                                                                    |
          "data: {"+                                                                                          |
          "floorplan_count: '#{property.available_floorplans(@s).length}',"+                                  |
          "link: '#{subdomain == 'gca' ? listing_path(property) : property_path(property)}',"+                                                              |
          "id: '#{property.id}',"+                                                                            |
          "image: '#{property.images.count > 0 ? property.images.first.thumb.url : '/images/no_image.gif'}',"+  |
          "title: '#{property.name.gsub("'","\\\'")}',"+                                                       |
          "rent: '#{rent_range(property.available_floorplans(@s))}'"+                                         |
          "},"+                                                                                               |
          "lat: #{property.latitude},"+                                                                       |
          "lng: #{property.longitude}"+                                                                       |
          "});"                                                                                               |
    - if units && units.length > 0                           
      - @units.reverse.each do |unit|
        = "points.push({"+                                                                                                                  |
          "data: {"+                                                                                                                        |
          "floorplan_count: '#{unit.floorplan.property.available_floorplans(@s).length}',"+                                                     |
          "link: '#{subdomain == 'gca' ? listing_path(unit.floorplan.property) : property_path(unit.floorplan.property)}',"+                                                                             |
          "id: '#{unit.floorplan.property.id}',"+                                                                                           |
          "image: '#{unit.floorplan.property.images.count > 0 ? unit.floorplan.property.images.first.thumb.url : '/images/no_image.gif'}',"+  |
          "title: '#{unit.floorplan.property.name}',"+                                                                                       |
          "rent: '#{rent_range(unit.floorplan.property.available_floorplans(@s))}'"+                                         |
          "},"+                                                                                                                             |
          "lat: #{unit.floorplan.property.latitude},"+                                                                                      |
          "lng: #{unit.floorplan.property.longitude}"+                                                                                      |
          "});"                                                                                                                             |
    GMap.addCommunityMarkers(points);
    GMap.addCenterMarker();
  GMap.finish();
  });

app/views/find/_schedule.html.haml
#schedule_visit.jump
  %h2 Request Information
  = form_for(schedule, :url => type == 'unit' ? floorplan_path(@floorplan, :unit_id => @unit) : property_path(property), html: {honeypot: true}) do |form|
    %fieldset
      .row
        .input.text.required
          = form.label :first_name, 'Your Name <b>required</b>'.html_safe
          = form.text_field :first_name, :placeholder => 'First'
          = form.error_message_on :first_name, :prepend_text => 'First Name '
        .input.text.last_name.required.last
          = form.label :last_name, 'Last Name'
          = form.text_field :last_name, :placeholder => 'Last'
          = form.error_message_on :last_name, :prepend_text => 'Last Name '
      .row
        .input.text.required
          = form.label :phone, 'Phone <b>required</b>'.html_safe
          = form.text_field :phone
          = form.error_message_on :phone, :prepend_text => 'Phone '
        .input.text.last
          = form.label :alt_phone, 'Alt. Phone'
          = form.text_field :alt_phone
      .input.text.required
        = form.label :email, 'Email <b>required</b>'.html_safe
        = form.text_field :email, :autocapitalize => 'off', :autocorrect => 'on'
        .option
          = check_box_tag 'schedule[opt_in]', true, false, :id => 'opt_in'
          = label_tag :opt_in, 'Send me updates from Gables Residential'
          %a{:title => 'Privacy Policy', :href => '/privacy', :class => 'inline'} privacy policy
        = form.error_message_on :last_name, :prepend_text => 'Email '
      .row
        .input.text
          = form.label :beds, 'Beds'
          = form.text_field :beds
          = form.error_message_on :beds, :prepend_text => 'Beds '
        .input.text.last
          = form.label :rent_range, 'Rent Range'
          = form.text_field :rent_range
          = form.error_message_on :rent_range, :prepend_text => 'Rent Range '
      .input.textarea
        = form.label :comments, 'How May We Help You?'
        = form.text_area :comments
        = form.error_message_on :comments, :prepend_text => 'Comments '
      .input.date
        = form.label :move_date, 'Move In Date'
        = form.text_field :move_date, :placeholder => 'DD / MM / YYYY', :autocomplete => 'off'
      .input.date.schedule
        = form.label :visit_date1, 'Schedule a Visit: Preferred Day and Time'
        .row
          .input.date
            = form.text_field :visit_date1, :placeholder => 'DD / MM / YYYY', :autocomplete => 'off'
          .input.select
            = form.select :visit_time1, options_for_select(schedule.times, params[:visit1_time])
      .submit
        - if schedule.errors.count > 0
          .error_explanation
            %p #{schedule.errors.count} errors prohibited your schedule from being saved. Please fix these errors and resubmit.
        %button{:type => 'submit'} Submit
        %p One of our leasing specialists will contact you within 24 hours.
  .contact_info
    - if property.images.count > 0
      .thumb= link_to image_tag(property.images.first.url, :alt => ''), property_path(property)
    %p <strong>#{property.name}</strong>
    %div{:itemprop => 'address', :itemscope => true, :itemtype => 'http://schema.org/PostalAddress'}
      %p{:itemprop => 'streetAddress'}= property.street
      %p 
        %span{:itemprop => 'addressLocality'} #{property.city}, 
        %span{:itemprop => 'addressRegion'} #{property.state} 
        #{property.zip}
    %p{:itemprop => 'telephone', :class => 'tel'}= property.phone

app/views/find/_walkscore_map.html.haml
:javascript
  var ws_wsid = 'fa7bbaf7196843fb90979fb913048f6a';
  var ws_address = "#{property.street},  #{property.city} #{property.state} #{property.zip}";
  var ws_map_icon_type = 'building';
  var ws_width = '640';
  var ws_height = '430';
  var ws_layout = 'horizontal';
  var ws_transit_score = 'true';
  var ws_commute = 'true';
  var ws_map_modules = 'all';
#ws-walkscore-tile
- content_for :javascripts do
  = javascript_include_tag 'http://www.walkscore.com/tile/show-walkscore-tile.php'

app/views/find/floorplan.html.haml
- content_for :head do
  %title= "#{@floorplan.property.name} Floorplans for Rent with photos and pricing - Luxury #{@floorplan.property.city} #{@floorplan.property.state}. Apartments by Gables Residential"
  %meta{:name => 'description', :content => "Rent a beautiful #{@floorplan.name} #{@property.name} unit in #{@floorplan.property.city}, #{@floorplan.property.state}. Furnished, Unfurnished, and Corporate options available. Free apartment finder and rentals search at Gables.com makes it easy."}
  = stylesheet_link_tag 'property'

#property.floorplan
  %div{:class => 'main_content', :itemscope => true, :itemtype => 'http://schema.org/Residence'}
    = link_to 'Back to community', property_path(@floorplan.property), :class => 'back'
    %p.community_name{:itemprop => 'name'}= link_to @floorplan.property.name, property_path(@floorplan.property)
    %h1= "#{@floorplan.name} #{@unit ? "#"+@unit.name : ""} - #{rooms(@floorplan)}"
    - if @floorplan.images.count > 0
      .images
        .main_image.floorplan_image{:itemprop => 'image'}= image_tag @floorplan.images.first.url
    #community_overview
      - unless @features.empty?
        %h2 Apartment Features
        .features{:itemprop => 'description'}
          %ul
            - @features.each do |amenity|
              %li= "- #{amenity.description}"
      .amenities
        %h3 Community Amenities
        %ul
          - @floorplan.property.amenities.each do |amenity|
            %li= "- #{amenity.description}"
      .options
        - if @unit && (@unit.from_vaultware || @unit.from_propertysolutions)
          .fp_availability
            %p Rent <strong>#{rent_range([@floorplan])}</strong>
            - if @property.use_propertysolutions_data?
              = link_to 'Apply Online', apply_online_url(@unit), :class => 'apply_online'
              = link_to 'Reserve / Pre-Qualify', reserve_prequalify_url(@unit, @floorplan, @property), :class => 'reserve_prequalify'
            - else
              = link_to 'Reserve This Unit & Apply Online', @unit.availability_url
        - elsif !@unit
          .fp_availability
            = link_to 'Notify Me When Available', ( @floorplan.use_propertysolutions_data? ? notify_me_when_available_url(@floorplan, @property) : @floorplan.availability_url )
        = render :partial => 'community_brochures'
    = render :partial => 'schedule', :locals => {:schedule => @schedule, :property => @floorplan.property, :type => 'unit'}
    #community_floorplans
      %h2 Recently Viewed
      .floorplans
        - @recently_viewed.each do |floorplan|
          - if floorplan.units.length > 0
            .floorplan
              .thumb
                - if floorplan.images.count > 0
                  = image_tag floorplan.images.first.thumb.url, :alt => ''
                - else
                  = image_tag 'no_image.gif', :alt => ''
              = render :partial => 'floorplan_table', :locals => {:floorplan => floorplan, :include_compare => false}
  = render :partial => 'community_sidebar', :locals => {:property => @floorplan.property, :type => 'unit'}

app/views/find/floorplans_serp.html.haml
- @property.available_floorplans(@s).each do |available_floorplan|
  - if available_floorplan.units.length > 0
    .floorplan
      .thumb
        - if available_floorplan.images.count > 0
          = link_to image_tag(available_floorplan.images.first.thumb.url, :alt => ''), floorplan_path(available_floorplan)
        - else
          = link_to image_tag('no_image.gif', :alt => ''), floorplan_path(available_floorplan)
      = render :partial => 'floorplan_table', :locals => {:floorplan => available_floorplan, :include_compare => true}
- unless params[:floorplans] && params[:floorplans] == 'now'
  .empty_floorplans
    - @property.unavailable_floorplans(@s).each do |unavailable_floorplan|
      .floorplan
        .thumb
          - if unavailable_floorplan.images.count > 0
            = link_to image_tag(unavailable_floorplan.images.first.thumb.url, :alt => ''), floorplan_path(unavailable_floorplan)
          - else
            = link_to image_tag('no_image.gif', :alt => ''), floorplan_path(unavailable_floorplan)
        %p <strong>#{unavailable_floorplan.name}</strong>
        %p= rooms(unavailable_floorplan)
        - if @property.from_vaultware?
          %p= link_to 'notify me when available', unavailable_floorplan.availability_url
        - else
          %p= link_to 'notify me when available', modal_contact_path(:@property => @property.id), :class => 'iframe'