config/routes.rb
Gables::Application.routes.draw do

  devise_for :users
  match '/admin/clear_cache' => 'application#clear_cache'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  constraints :subdomain => /^tablet/ do
    root  :to => 'tablet/properties#index'
    resources :properties, :only => [:index, :show, :edit], :as => "tablet_properties", :module => "tablet" do
      get 'manifest', :on => :member, :as => 'manifest'
      get "floorplans", :on => :member
      get "options", :on => :member
      post "email_brochure", :on => :member
      post "email_pdf", :on => :member
      resources :units, :only => [:index] do
        post "expire", :on => :collection
        get "nearby", :on => :collection
      end
    end
    resources :guests, :as => "tablet_guests", :module => "tablet"
    match 'samples' => "tablet/properties#samples"

    post 'sessions/create' => "tablet/sessions#create", :as => "tablet_create_sessions"
    put  'sessions' => "tablet/sessions#update"
    get  'sessions/status' => "tablet/sessions#status"
    post 'sessions/destroy' => "tablet/sessions#destroy"
    match "/find-guest" => "tablet/insite#find_guest"
    match "/guest-card" => "tablet/insite#guest_card"
    post "/submit-guest-card" => "tablet/insite#submit_guest_card"
  end

  constraints :subdomain => /urban/ do
    root :to => 'urban/home#index'
    match 'modal/contact'       => 'modal#contact'
    match 'modal/thankyou'      => 'modal#thankyou'
    match 'home/site_search'    => 'urban/home#site_search'
    match 'properties'          => 'urban/home#properties'
    match 'find/apartment/:id'  => 'urban/find#community'
    match 'find/where'  => 'urban/find#where'
    match 'modal/video'         => 'modal#video'
    match 'company/news/:id'    => 'company#news_show', :as => 'post'
    match 'company/news'        => 'company#news',      :as => 'posts'
    match ':section/p/:path'    => 'urban/pages#show', :as => 'urban_page',
          :constraints => {:section => /services|toplevel/}
  end

  constraints :subdomain => /gca/ do
    root  :to                   => 'gca/home#index'
    match 'gallery'             => 'gca/home#gallery'
    post 'contact'             => 'gca/home#contact'
    match 'modal/contact'       => 'modal#contact'
    match 'modal/thankyou'      => 'modal#thankyou'
    match 'find/where'          => 'gca/find#where'
    match 'find/listing/:id'  => 'gca/find#community', :as => 'listing'
    match 'find/walkscore/:id'  => 'find#walkscore', :as => 'walkscore'
    match 'modal/video'         => 'modal#video'
    match 'home/site_search'    => 'gca/home#site_search'
    post 'home/maintenance_request'  => 'gca/home#maintenance'
    post 'home/lease_request'  => 'gca/home#lease'
    match 'thank_you'           => 'gca/home#thank_you'
    match 'company/news/:id'    => 'company#news_show', :as => 'post'
    match 'company/news'        => 'company#news',      :as => 'posts'
    match 'equal_employment'    => 'home#equal_employment', :as => 'equal_employment'
    match ':section/p/:path'    => 'gca/pages#show', :as => 'gca_page',
          :constraints => {:section => /services|toplevel/}

    match '/gca-living.aspx'                                => redirect('/toplevel/p/our_company')
    match '/gca-gablesservices.aspx'                        => redirect('/services/p/guest_services')
    match '/gca-careers.aspx'                               => redirect('http://gables.com/careers/p/careers_overview')
    match '/gca-contactus.aspx'                             => redirect('/toplevel/p/our_company')
    match '/home.aspx'                                      => redirect('/')
    match '/gca-living/gca-reservation.aspx'                => redirect('/contact')
    match '/gca-living/gca-furnishings.aspx'                => redirect('/gallery')
    match '/gca-living/gca-tour.aspx'                       => redirect('/gallery')
    match '/gca-living/gca-faq.aspx'                        => redirect('/services/p/how_it_works')
    match '/gca-gablesservices/gca-servicerequest.aspx'     => redirect('/services/p/guest_services')
    match '/gca-gablesservices/gca-testimonials.aspx'       => redirect('/services/p/how_it_works')
    match '/gca-gablesservices/gca-vacate.aspx'             => redirect('/services/p/guest_services')
    match '/gca-living/green-initiatives.aspx'             => redirect('http://gables.com/life/p/green_initiatives')

  end

  constraints :subdomain => /(?!gca|urban|tablet)/ do
    root :to => 'find#index'

    get "language" => "home#language"
    match 'contact'           => 'home#contact'
    match 'tablet'            => 'home#tablet'
    match 'equal_employment'  => 'home#equal_employment', :as => 'equal_employment'
    match 'privacy'           => 'home#privacy',          :as => 'privacy'
    match 'vaultware'         => 'home#vaultware',        :as => 'vaultware'
    match 'recent_searches'   => 'home#recent_searches',  :as => 'recent_searches'

    match ':section/p/:path'  => 'pages#show', :as => 'page',
          :constraints => {:section => /life|company|careers/}

    match   'find/apartment/:id'  => 'find#community', :as => 'property'
    match   'find/floorplan/:id'  => 'find#floorplan', :as => 'floorplan'
    match   'find/walkscore/:id'  => 'find#walkscore', :as => 'walkscore'

    match   'yelp/:id'  => 'find#yelp', :as => 'yelp'

    namespace 'find' do
      get   'where'
      post  'where'
      get   'comparison'
      get   'request_hold'
      get   'floorplans_serp'
    end

    namespace 'home' do
      get   'site_search'
      get   'empty'
    end

    namespace 'life' do
      get 'why_gables'
    end

    match 'company/news/:id'  => 'company#news_show', :as => 'post'
    match 'company/news'      => 'company#news',      :as => 'posts'

    namespace 'modal' do
      get   'thankyou'
      get   'contact'
      get   'video'
      get   'executive'
      post   'contact'
    end

    namespace 'sectionals' do
      get   'header'
      get   'footer'
    end

    namespace 'associates' do
      get   'show'
    end

    match   'associates/show/:id'  => 'associates#show', :as => 'associate'
    get 'sitemap.:format' => 'sitemap#show', :as => :sitemap, :constraints => {:format => 'xml'}

    match '/find/community/:any'                          => redirect('/find/apartment/%{any}')
    match '/aboutus.aspx'                                 => redirect('/life/p/why_gables')
    match '/aboutus/awards.aspx'                          => redirect('/company/news')
    match '/aboutus/community-service.aspx'               => redirect('/life/p/community_service')
    match '/aboutus/company-overview.aspx'                => redirect('/company/p/corporate_overview')
    match '/aboutus/company-philosophy.aspx'              => redirect('/life/p/why_gables')
    match '/aboutus/construction-and-development.aspx'    => redirect('/company/p/real_estate')
    match '/aboutus/copyright.aspx'                       => redirect('/privacy')
    match '/aboutus/gablesgreeninitiative.aspx'           => redirect('/life/p/green_initiatives')
    match '/aboutus/gablesgreeninitiative/earthday.aspx'  => redirect('/life/p/green_initiatives')
    match '/aboutus/gablesmessage.aspx'                   => redirect('/life/p/community_service')
    match '/aboutus/in-the-news.aspx'                     => redirect('/company/news')
    match '/aboutus/investmentstrategy.aspx'              => redirect('/company/p/real_estate')
    match '/aboutus/officers.aspx'                        => redirect('/company/p/corporate_executives')
    match '/aboutus/privacypolicy.aspx'	                  => redirect('/privacy')
    match '/aboutus/property-management.aspx'	            => redirect('/company/p/real_estate')
    match '/aboutus/sitemap.aspx'	                        => redirect('/')
    match '/aboutus/whotocontact.aspx'	                  => redirect('/company/p/corporate_contacts')
    match '/admin.:any'	                                  => redirect('/admin')
    match '/apartment-living/:any/:any'	                  => redirect('/life/p/why_gables')
    match '/around-town/:any/:any'                        => redirect('/')
    match '/careers.aspx'	                                => redirect('/careers/p/careers_overview')
    match '/carrers.aspx'	                                => redirect('/careers/p/careers_overview')
    match '/careers'                                      => redirect('/careers/p/search')
    match '/contactus.:any'	                              => redirect('/company/p/corporate_contacts')
    match '/gablesliving/:any'	                          => redirect('/life/p/why_gables')
    match '/gablesservices.:any'	                        => redirect('/company/p/corporate_overview')
    match '/gca-:any'	                                    => redirect('http://gca.gables.com/')
    match '/holiday2010/:any'                             => redirect('/')
    match '/home'	                                        => redirect('/')
    match '/index.:any'                                   => redirect('/')
    match '/intersource:any'                              => redirect('/')
    match '/jobs/:any'	                                  => redirect('/careers/p/careers_overview')
    match '/new:any'	                                    => redirect('/')
    match '/onlineleasing/:any'	                          => redirect('https://extra.gables.com/portal/')
    match '/portallogin.:any'                             => redirect('https://extra.gables.com/portal/')
    match '/post/:any'                                  	=> redirect('http://blog.gables.com/')
    match '/RequestConfirm.:any'	                        => redirect('/')
    match '/RequestPreQualify.:any'	                      => redirect('/')
    match '/RequestToHold.:any'                         	=> redirect('/')
    match '/RequestVIP.:any'                            	=> redirect('/')

app/controllers/gca/home_controller.rb
class Gca::HomeController < Gca::ApplicationController
  layout 'gca/application'
  
  def index
    @promos = Gca::Promo.by_position_asc.limit(3)
    @sliders = Gca::HomeSlide.by_position_asc
    @footer_news = Post.featured.limit(3)
  end
  
  def gallery
    @section = 'services'
  end
  
  def contact
    if params[:gca_contact].blank?
      @contact = Gca::Contact.new(params[:contact] ? params[:contact] : nil)
    else
      @contact = Gca::Contact.new(params[:gca_contact])
      if @contact.valid?
        Gca::ContactMailer.deliver_contact @contact
        redirect_to '/thank_you'
      end
    end
  end
  
  def maintenance
    @maintenance = Gca::MaintenanceRequest.new(params[:maintenance])
    if @maintenance.valid?
      Gca::ContactMailer.deliver_maintenance @maintenance if params[:a_comment_body].blank?
      redirect_to '/thank_you'
    end
  end
  
  def lease
    @lease = Gca::LeaseRequest.new(params[:lease])
    if @lease.valid?
      Gca::ContactMailer.deliver_lease @lease if params[:a_comment_body].blank?
      redirect_to '/thank_you'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
    @regions = Region.all
  end

  def equal_employment
    @section = 'careers'
  end

  def privacy
    @section = 'company'
  end
  
  def vaultware
    ActionController::Base.asset_host = request.host_with_port
    render :layout => 'sectional'
  end
  
  def recent_searches
    @searches = UserSearch.order('updated_at desc').limit(2000)
  end

  def tablet
    render :layout => 'tablet'
  end

  def language
    render :text => request.headers["HTTP_ACCEPT_LANGUAGE"]
  end
end

app/controllers/urban/home_controller.rb
class Urban::HomeController < ApplicationController
  layout 'urban/application'

  def index
    @sliders = Urban::HomeSlide.by_position_asc
    @footer_news = Post.featured.limit(3)
    @promos = Urban::Promo.by_position_asc.limit(3)
  end
  
  def properties
    @section = 'properties'
    @properties = Urban::Property.order('position ASC')
    @cities = Urban::Property.select("DISTINCT(city)").order('city').map(&:city)
  end
end

app/views/home/contact.html.haml
- content_for :head do
  %title Contact

%h2 Corporate
%p Phone
%p
%p Address
%p 

%h2 Communities
%ul
  - @regions.each do |region|
    %li
      %p= region.name
      %ul
        - region.properties.published.each do |property|
          %li
            %p= property.address
            %p= property.phone
            = link_to 'contact form', modal_contact_path(:property => property.id), :class => 'iframe'
    %li
      %p Other
      %ul
        - Property.without_region.each do |property|
          %li
            %p= property.address
            %p= property.phone
            = link_to 'contact form', modal_contact_path(:property => property.id), :class => 'iframe'

app/views/home/empty.haml
- content_for :head do
  = stylesheet_link_tag 'pages'

- content_for :marquee do
  #marquee.inner
    .wrapper
      .item

          
#inner_page
  %article.main_content
    Main Content
  
  %aside.sub_content
    Sub Content

app/views/home/equal_employment.html.haml
- content_for :head do
  %title Equal Employment Opportunities
  = stylesheet_link_tag 'pages'
  
- content_for :marquee do
  #marquee.inner
    .wrapper
      .item
        =image_tag 'careers-header.jpg', :alt => ''

#inner_page
  %article.main_content
    .border
      .feature.large
        %h2#equal_opportunity.title Equal Employment Opportunities

      %p Gables Residential provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, gender, sexual orientation, national origin, age, disability, genetic information, marital status, , or status as a veteran in accordance with applicable federal, state and local laws. Gables Residential complies with applicable state and local laws governing non-discrimination in employment in every location in which the company has facilities. This policy applies to all terms and conditions of employment, including, but not limited to, hiring, placement, promotion, termination, layoff, recall, transfer, leaves of absence, compensation, and training.

      %p Gables Residential expressly prohibits any form of unlawful employee harassment based on race, color, religion, gender, sexual orientation, national origin, age, genetic information, marital status, disability, or veteran status. Improper interference with the ability of Gables' employees to perform their expected job duties is absolutely not tolerated.
    
    .feature.large
      %h2#fair_housing.title Fair Housing and ADA
    %p Gables is pledged to the letter and spirit of U. S. policy for the achievement of equal housing opportunity throughout the nation.  Gables operates in accordance with the Fair Housing Act (the Civil Rights Act or 1968, as amended by the Fair Housing Amendments Act of 1988), the Americans with Disabilities Act as well as all applicable local and state laws regarding fair housing and equal opportunity.

    %p It is our goal to provide equal opportunity housing to all persons, and we do not discriminate based on race, color, national origin, religion, sex, veteran status, disability or familial status. We provide periodic training for all of our employees who oversee rentals to ensure compliance.  For many years Gables has worked with design professionals to assure that its apartment homes provide accessibility. This will continue to be accomplished in our training, education, “best practice” guidance, compliance testing and accessibility resources for future developments. We are committed to providing fair housing to its residents with disabilities and to provide reasonable accommodations to persons with disabilities.We encourage and support an affirmative advertising and marketing program. Gables will not make, print, or publish, or cause to be made, printed or published, any notice, statement, or advertisement, with respect to the sale or rental of a dwelling that indicates any preference, limitation, or discrimination based on race, color, religion, sex, disability, familial status, or national origin, or an intention to make any such preference, limitation, or discrimination. To help accomplish this commitment Gables:
    
    %p Gables Residential will not knowingly advertise real estate in any manner that violates the law. All persons are hereby informed that all dwellings advertised on this website are available on an equal opportunity basis.

app/views/home/privacy.html.haml
- content_for :head do
  %title Privacy Policy
  = stylesheet_link_tag 'pages'
  
- content_for :marquee do
  #marquee.inner
    .wrapper
      .item
        =image_tag 'company-header.jpg', :alt => ''

#inner_page
  %article.main_content
    .feature.large
      %h2.title Privacy Policy
      %p.description Terms of Use

    .feature
      %h3.title Use of Copyrighted Materials/Trademarks

      %p Any materials on the Website, including without limitation any documentation, content, text, data, graphics, images, video and audio clips, interfaces or other materials, information or works of authorship are copyrighted materials (i) owned by Gables Residential (collectively, the “Materials”) or (ii) provided by third party licensors and suppliers to Gables Residential (collectively, the “Third Party Content”). All rights not expressly granted in and to the Website, the Materials and the Third Party Content are reserved to their respective owners, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. You agree to abide by all copyright notices and trademark, information and other restrictions in connection with the Website, including without limitation any Materials and Third Party Content therein. 

      %p The Materials contain trademarks, service marks and trade names, which are owned by Gables and its affiliates. Except as otherwise noted in the Website, you are hereby authorized to view, download, cache, copy and print the Materials solely for your personal, non-commercial use and not for resale or further distribution, retransmission, subject to the following conditions: 

      %ol.description
        %li Any copy of the Materials or portion thereof must include all copyright notices appearing on the original.
        %li Gables Residential reserves the right to revoke such authorization at any time, and any such use by you shall be discontinued immediately upon notice from Gables Residential. 

      %p The Third Party Content may also contain brand and product names, which are trademarks, service marks or trade names of third parties, which are the property of their respective owners. Unless you have permission from the owner of the Third Party Content, you agree only to display the Third Party Content on your personal computer solely for your personal or internal business use. You acknowledge and agree that you have no right to download, cache, reproduce, modify, distribute, display (except as set forth in this paragraph), edit, alter or enhance any of the Third Party Content in any manner unless you have permission from the owner of the Third Party Content. You acknowledge and agree that the Third Party Content does not reflect the views of Gables Residential and that Gables Residential is not responsible for any views, ideas, positions, materials and the like contained in any Third Party Content. 

      %p Nothing contained in the Website shall be construed as conferring any license or right under any copyright, trade secret, patent, trademark or other intellectual property rights (“IP Rights”) of Gables Residential, its affiliates, or any third party, and, except as expressly provided herein, all such IP Rights in the Materials and Third Party Content on the Website are expressly reserved to Gables Residential, its affiliates, and/or any third party, as applicable. Without limiting the generality of the foregoing, unless you have the express prior written consent of Gables Residential or written permission from a third party with respect to such party’s Third Party Content, you may not (i) distribute the Website, or any portion thereof or content (including without limitation Materials and Third Party Content) of any kind included therein, in any medium, (ii) modify the Website, or any portion thereof, (iii) access the Materials and Third Party Content through any technology or means other than those provided on the Website itself, (iv) use the Website, or any portion thereof or content of any kind included therein, in any medium, for any commercial use, or (v) transmit, broadcast, display, sell, license or otherwise exploit the Website (including without limitation Materials and Third Party Content) for any other purpose whatsoever without the prior written consent of the respective owners.

      %p You are granted a limited, nonexclusive right to create a "hypertext" link to the Website provided that such link is to the entry or home page of this Website and does not portray Gables Residential or any of its products or services in a false, misleading, derogatory, or otherwise defamatory manner. This limited right may be revoked by Gables Residential at any time for any reason whatsoever. You may not use, frame, or utilize framing techniques to enclose any Gables Residential trademark, logo or trade name or other proprietary information including the Materials found at or on the Website, the content of any text or the layout/design of any page of the Website or any form contained on a page of the Website without the express prior written consent of Gables Residential in each instance. In addition, you may not use any meta-tags or any other "hidden text" utilizing a Gables Residential or Gables Residential affiliate name, trademark, or product name without Gables Residential express written consent in each instance.

      %h3.title Links to Third Party Websites

      %p The Website may be linked to other websites on the World Wide Web or Internet that are not affiliated with, under the control of, or otherwise maintained by Gables Residential. If you use these links, you may leave the Website. Gables Residential has not reviewed any of these third party sites and does not control and is not responsible for any of these sites or their content. Gables Residential does not endorse any opinion, recommendation or advice expressed therein or make any representations about third party sites, their usefulness, safety or intellectual property rights of or relating to such content, or any information or other products, services or materials found there, or any results that may be obtained from using them, and Gables Residential expressly disclaims any and all liability in connection with such third party sites. You understand and acknowledge that you may be exposed to content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive and hereby do waive, any legal or equitable rights or remedies you have or may have against Gables Residential in connection therewith. You further understand and acknowledge if you decide to access any of the third party sites linked to the Website, you do so entirely at your own risk. 

      %h3.title Noninterference

      %p You shall not circumvent, disable or otherwise interfere with security-related features of the Website or features that filterCitiesByState or restrict use or copying of any Materials and/or Third Party Content or enforce limitations on use of the Website or any such content therein.

app/views/home/recent_searches.html.haml
- content_for :head do
  %title Recent Searches
  = stylesheet_link_tag 'pages'

#inner_page
  %article.main_content
    %ul.recent_searches
      - @searches.each do |search|
        %li=link_to search.query, find_where_path(:query => search.query)

app/views/home/site_search.html.haml
- content_for :head do
  %title Site Search
  = javascript_include_tag 'http://www.google.com/jsapi'
  = stylesheet_link_tag 'http://www.google.com/cse/style/look/default.css'
  
#inner_page{:style => 'padding-top: 25px'}
  #cse_search_results &nbsp;
  :javascript
    google.load("search", "1", {"nocss" : true});
    var googleSearchIframeName = "cse_search_results";
    var googleSearchFormName = "cse_search_box";
    var googleSearchFrameWidth = 940;
    var googleSearchDomain = "www.google.com";
    var googleSearchPath = "/cse";
  = javascript_include_tag 'http://www.google.com/afsonline/show_afs_search.js'

app/views/home/vaultware.html.haml
- content_for :head do
  %title= "Gables offers Apartments for Rent, Luxury Apartments, Furnished Apartments, Unfurnished Apartments and Corporate Housing"
  %meta{:name => 'description', :content => "Gables features luxury apartments for rent including unfurnished, furnished apartments, and corporate housing. Free apartment finder and rentals search at Gables.com makes it easy."}
  = stylesheet_link_tag 'pages'

= render :partial => '/shared/header', :locals => {:context => 'external'}
%section#main_content
  #inner_page
    %article.main_content
      %a{:href => '#', :class => 'vaultware_back', :onclick => 'javascript: window.history.back(); return false;'} &laquo; Back
      VAULTWARE-GOES-HERE
  
    %aside.sub_content
      = render :partial => '/shared/blog_sidebar'
= render :partial => '/shared/footer', :locals => {:context => 'external'}